### ISSUE TITLE
Display already faved / retweetet tweets properly

### ISSUE THREAD

**Issue by nicoknoll** [HPI-SWA-Teaching/SWT16-Project-16#14]
If you load a tweet so far fav and retweet will not be shown as "active". They only switch state to active if you click them.

**Comment by nikriek** [comment]
Works already

**Comment by nikriek** [comment]
https://github.com/HPI-SWA-Teaching/SWT16-Project-16/commit/dca31b87e7d6933797a160c5bdfe4cff1a77e01a
